name: YouTube Live Stream Loop

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg & gdown
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip install --upgrade gdown

      - name: Download Video from Drive
        run: |
          gdown 'https://drive.google.com/uc?export=download&id=16Sl-wOplNoJVMRTEhls2yA1iN-fzu-pN' -O input.mp4

      - name: Start Live Stream (Original Quality - No Filter)
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: |
          timeout 21000 ffmpeg -re -stream_loop -1 -i input.mp4 \
          -c:v copy \
          -c:a copy \
          -f flv "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY" || true

      - name: Trigger Next Workflow Run Automatically
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh workflow run main.yml -R ${{ github.repository }}
