
name: YouTube Live Stream Loop

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video from Drive
        run: |
          curl -L -c cookies.txt "https://drive.google.com/uc?export=download&id=16Sl-wOplNoJVMRTEhls2yA1iN-fzu-pN&confirm=$(curl -s -c cookies.txt 'https://drive.google.com/uc?export=download&id=1M11BJEjVaI1UbInyNIVF1qSavG5V' | grep -o 'confirm=[^&]*' | cut -d= -f2)" -o video.mp4

      - name: Start Live Stream
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: |
          timeout 21000 ffmpeg -re -stream_loop -1 -err_detect ignore_err -i video.mp4 \
          -c:v libx264 -preset ultrafast -b:v 3000k -maxrate 3000k -bufsize 6000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY" || true

      - name: Trigger Next Workflow Run Automatically
        env:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/stream.yml/dispatches \
            -d '{"ref":"main"}'
